controllers:
  joint3_calibration_controller:
    type: rm_calibration_controllers/JointCalibrationController
    joint: joint3
    actuators: [ joint3_motor ]
    search_velocity: -4.0
    threshold: 0.1
    pid: { p: 3, i: 0, d: 0, i_clamp_max: 0, i_clamp_min: 0, antiwindup: true }
