controllers:
  mast_calibration_controller:
    type: rm_calibration_controllers/JointCalibrationController
    joint: mast_joint
    actuators: [ mast_joint_motor ]
    search_velocity: 0.2
    threshold: 0.01
    pid: { p: 1000.0, i: 0.0, d: 0.0, i_clamp_max: 0, i_clamp_min: 0.0, antiwindup: true }
    return:
      joint: joint4
      actuators: [ joint4_motor ]
      target_position: 0
      threshold: 0.0001
      pid: { p: 8000.0, i: 0, d: 350, i_clamp_max: 0, i_clamp_min: 0, antiwindup: true, publish_state: true }