language: generic
services:
  - docker

env:
  matrix:
    - ROS_DISTRO="noetic" UPSTREAM_WORKSPACE='github:rm-controls/rm_control#master -rm_control/rm_base -rm_control/rm_description -rm_control/rm_gazebo'
    - ROS_DISTRO="melodic" UPSTREAM_WORKSPACE='github:rm-controls/rm_control#master -rm_control/rm_base -rm_control/rm_description -rm_control/rm_gazebo'

install:
  - git clone --quiet --depth=1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master

before_script:
  - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"

script:
  - .industrial_ci/travis.sh
  - fossa init
  - fossa analyze

after_success:
  - cd <SOURCE_DIR> && fossa test

notifications:
  webhooks: https://app.fossa.io/hooks/travisci