controllers:
  left_tof_sensor_controller:
    type: tof_sensor_controller/Controller
    name: "left_chassis_tof"
  right_tof_sensor_controller:
    type: tof_sensor_controller/Controller
    name: "right_chassis_tof"
