controllers:
  robot_state_controller:
    type: robot_state_controller/RobotStateController
    publish_rate: 50
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  gimbal_standard_controller:
    type: rm_gimbal_controllers/GimbalStandardController
    joint_yaw_name: "yaw_joint"
    joint_pitch_name: "pitch_joint"
    pid_yaw: { p: 6, i: 0.08, d: 0.01, i_clamp_max: 0.2, i_clamp_min: -0.2, antiwindup: true, publish_state: true }
    pid_pitch: { p: 10, i: 7.0, d: 0.08, i_clamp_max: 0.8, i_clamp_min: -0.8, antiwindup: false, publish_state: true }
    time_compensation: 0.004
    bullet_solver:
      resistance_coff_qd_10: 0.45
      resistance_coff_qd_15: 0.4
      resistance_coff_qd_16: 0.7
      resistance_coff_qd_18: 0.55
      resistance_coff_qd_30: 3.0
      g: 9.81
      delay: 0.2
      dt: 0.001
      timeout: 0.001
      publish_rate: 50