controllers:
  robot_state_controller:
    type: robot_state_controller/RobotStateController
    publish_rate: 50
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  shooter_controller:
    type: rm_shooter_controllers/StandardController
    joint_friction_left_name: "left_friction_wheel_joint"
    joint_friction_right_name: "right_friction_wheel_joint"
    joint_trigger_name: "trigger_joint"
    enter_push_qd_coef: 0.95
    push_angle: 0.8
    push_angle_error: 0.04
    block_effort: 0.9
    block_duration: 0.05
    block_speed: 0.5
    anti_block_angle: 0.15
    anti_block_error: 0.1
    qd_15: 474.0
    qd_18: 520.0
    qd_30: 714.0
    pid_friction_l: { p: 0.001, i: 0.01, d: 0.0, i_clamp_max: 0.01, i_clamp_min: -0.01, antiwindup: true, publish_state: true }
    pid_friction_r: { p: 0.001, i: 0.01, d: 0.0, i_clamp_max: 0.01, i_clamp_min: -0.01, antiwindup: true, publish_state: true }
    pid_trigger: { p: 18.4, i: 0.0, d: 0.6, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true, publish_state: true }
    publish_rate: 50
