controllers:
  robot_state_controller:
    type: robot_state_controller/RobotStateController
    publish_rate: 100
  imu_sensor_controller:
    type: imu_sensor_controller/ImuSensorController
    publish_rate: 100

  chassis_controller:
    type: rm_chassis_controllers/SwerveController
    modules:
      left_front:
        position: [ 0.2, 0.2 ]
        pivot:
          name: left_front_pivot_joint
          offset: 0.
          pid: { p: 0., i: 0., d: 0., i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
        wheel:
          name: left_front_wheel_joint
          radius: 0.05
          pid: { p: 0., i: 0., d: 0., i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
      right_front:
        position: [ 0.2, -0.2 ]
        pivot:
          name: right_front_pivot_joint
          offset: 0.
          pid: { p: 0., i: 0., d: 0., i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
        wheel:
          name: right_front_wheel_joint
          radius: 0.05
          pid: { p: 0., i: 0., d: 0., i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
      left_back:
        position: [ -0.2, 0.2 ]
        pivot:
          name: left_back_pivot_joint
          offset: 0.
          pid: { p: 0., i: 0., d: 0., i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
        wheel:
          name: left_back_wheel_joint
          radius: 0.05
          pid: { p: 0., i: 0., d: 0., i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
      right_back:
        position: [ -0.2, -0.2 ]
        pivot:
          name: left_back_pivot_joint
          offset: 0.
          pid: { p: 0., i: 0., d: 0., i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
        wheel:
          name: left_back_wheel_joint
          radius: 0.05
          pid: { p: 0., i: 0., d: 0., i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100