controllers:
  robot_state_controller:
    type: robot_state_controller/RobotStateController
    publish_rate: 100
  imu_sensor_controller:
    type: imu_sensor_controller/ImuSensorController
    publish_rate: 100

  chassis_controller:
    type: rm_chassis_controllers/SwerveController
    publish_rate_: 100
    enable_odom_tf: true
    twist_covariance_diagonal: [ 0.001, 0.001, 0.001, 0.001, 0.001, 0.001 ]
    modules:
      left_front:
        position: [ 0.2, 0.2 ]
        pivot:
          name: left_front_pivot_joint
          <<: &pivot_setting
            offset: 0.
            pid: { p: 3, i: 0, d: 0.3, i_clamp_max: 0, i_clamp_min: 0, antiwindup: true, publish_state: true }
        wheel:
          name: left_front_wheel_joint
          <<: &wheel_setting
            radius: 0.055
            pid: { p: 0.8, i: 0, d: 0.0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
      right_front:
        position: [ 0.2, -0.2 ]
        pivot:
          name: right_front_pivot_joint
          <<: *pivot_setting
        wheel:
          name: right_front_wheel_joint
          <<: *wheel_setting
      left_back:
        position: [ -0.2, 0.2 ]
        pivot:
          name: left_back_pivot_joint
          <<: *pivot_setting
        wheel:
          name: left_back_wheel_joint
          <<: *wheel_setting
      right_back:
        position: [ -0.2, -0.2 ]
        pivot:
          name: right_back_pivot_joint
          <<: *pivot_setting
        wheel:
          name: right_back_wheel_joint
          <<: *wheel_setting

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100