/*
 * File: leg_conv.c
 *
 * MATLAB Coder version            : 5.5
 * C/C++ source code generated on  : 10-Aug-2025 14:29:16
 */

/* Include Files */
#include "rm_chassis_controllers/balance/vmc/leg_conv.h"
#include <math.h>

/* Function Definitions */
/*
 * LEG_CONV
 *     T = LEG_CONV(F,Tp,PHI1,PHI2)
 *
 * Arguments    : double F
 *                double Tp
 *                double phi1
 *                double phi2
 *                double T[2]
 * Return Type  : void
 */
void leg_conv(double F, double Tp, double phi1, double phi2, double T[2])
{
  double t10_tmp;
  double t11_tmp;
  double t12_tmp;
  double t26;
  double t28;
  double t30;
  double t31;
  double t32;
  double t33;
  double t34;
  double t36;
  double t4;
  double t5;
  /*     This function was generated by the Symbolic Math Toolbox version 9.2.
   */
  /*     10-Aug-2025 14:28:23 */
  t4 = cos(phi1);
  t5 = sin(phi1);
  t10_tmp = phi1 + phi2;
  t11_tmp = cos(t10_tmp);
  t12_tmp = sin(t10_tmp);
  t26 = t11_tmp * 0.27;
  t28 = t12_tmp * 0.27;
  t30 = t4 * 0.15 + t26;
  t31 = t5 * 0.15 + t28;
  t32 = t30 * t30;
  t33 = t31 * t31;
  t34 = 1.0 / t33;
  t36 = 1.0 / (t32 + t33);
  t4 = t4 * 0.15 + t11_tmp * 0.27;
  t10_tmp = t5 * 0.15 + t12_tmp * 0.27;
  T[0] = -Tp * t33 * t36 * (t32 * t34 + 1.0);
  T[1] =
      F * (t12_tmp * (t11_tmp * 0.27 + cos(phi1) * 0.15) * 0.54 - t11_tmp * (t12_tmp * 0.27 + sin(phi1) * 0.15) * 0.54) *
          -0.5 / sqrt(t4 * t4 + t10_tmp * t10_tmp) +
      Tp * t33 * t36 * ((0.0 - t28) / t31 - t30 * t34 * t26);
}

/*
 * File trailer for leg_conv.c
 *
 * [EOF]
 */
