/*
 * File: leg_spd.c
 *
 * MATLAB Coder version            : 5.5
 * C/C++ source code generated on  : 10-Aug-2025 14:30:13
 */

/* Include Files */
#include "rm_chassis_controllers/balance/vmc/leg_spd.h"
#include <math.h>

/* Function Definitions */
/*
 * LEG_SPD
 *     SPD = LEG_SPD(DPHI1,DPHI2,PHI1,PHI2)
 *
 * Arguments    : double dphi1
 *                double dphi2
 *                double phi1
 *                double phi2
 *                double spd[2]
 * Return Type  : void
 */
void leg_spd(double dphi1, double dphi2, double phi1, double phi2, double spd[2])
{
  double t29_tmp;
  double t30_tmp;
  double t33;
  double t34;
  double t35;
  double t37;
  double t8;
  double t9;
  /*     This function was generated by the Symbolic Math Toolbox version 9.2.
   */
  /*     10-Aug-2025 14:28:23 */
  t8 = phi1 + phi2;
  t9 = cos(t8);
  t8 = sin(t8);
  t29_tmp = cos(phi1) * 0.15 + t9 * 0.27;
  t30_tmp = sin(phi1) * 0.15 + t8 * 0.27;
  t33 = t29_tmp * t29_tmp;
  t34 = t30_tmp * t30_tmp;
  t35 = 1.0 / t34;
  t37 = 1.0 / (t33 + t34);
  spd[0] = dphi2 / sqrt(t29_tmp * t29_tmp + t30_tmp * t30_tmp) * (t9 * t30_tmp * 0.54 - t8 * t29_tmp * 0.54) / 2.0;
  spd[1] = -dphi1 * t34 * t37 * (t33 * t35 + 1.0) +
           dphi2 * t34 * t37 * ((0.0 - t8 * 0.27) / t30_tmp - t29_tmp * t35 * (t9 * 0.27));
}

/*
 * File trailer for leg_spd.c
 *
 * [EOF]
 */
